import type { Metadata } from "next";
import { Montserrat, Montserrat_Alternates, Instrument_Sans} from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const montserrat_alt = Montserrat_Alternates({
  variable: "--font-montserrat-alt",
  weight: "500",
  subsets: ["latin"]
});

const instrument_sans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets:["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${montserrat_alt.variable} ${instrument_sans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
